spring.application.name=TripSheep

spring.data.mongodb.uri=YOUR MONGO URL
spring.data.mongodb.database=mydb
logging.level.org.springframework.data.mongodb.core.MongoTemplate = DEBUG
logging.level.org.springframework.data.mongodb.core.MongoActionOperation = DEBUG
spring.main.allow-bean-definition-overriding=true

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR GMAIL ID
spring.mail.password=GMAIL APP PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
