spring.application.name=TripSheep

spring.data.mongodb.uri=mongodb+srv://nandviky4:vandan@cluster0.jp7wx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=mydb
logging.level.org.springframework.data.mongodb.core.MongoTemplate = DEBUG
logging.level.org.springframework.data.mongodb.core.MongoActionOperation = DEBUG
spring.main.allow-bean-definition-overriding=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vandannandwanaji@gmail.com
spring.mail.password=noxw eywg boof ezow
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true